name: word_carousel
description: A Flutter package for displaying animated sequential text with smooth transitions.
version: 0.0.1
homepage: https://github.com/Penguin5681/Word-Carousel

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: